jwt:
  key: ${JWT_KEY}

api:
  key: ${API_KEY}

validator:
  url: ${VALIDATOR_URL:http://host.docker.internal:3000/execute-shader}
  key: ${VALIDATOR_KEY}
  connect-timeout-ms: ${VALIDATOR_CONNECT_TIMEOUT_MS:2000}
  read-timeout-ms: ${VALIDATOR_READ_TIMEOUT_MS:15000}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
