spring:
  application:
    name: "auth"
  profiles:
    active: "private"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: "none" # Ensures JPA does not update or modify the schema
    properties:
      hibernate:
        show_sql: true   # Optional: Enable to log SQL queries
        format_sql: true


server:
  port: 8080



